---
title: "Development"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```


```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```



# f_get_admin2_boundaries
    
```{r function-f_get_admin2_boundaries}
#' Get admin2 polygons from API
#'
#' Queries the gis.unhcr.org sever to return admin2 shape files for a specific
#' country. Some of the files returned are heavy, and the server also seems to
#' fail or time out every now and then. Also, some admin2 codes are not in the
#' expected format.
#'
#' @param ISO3 ISO3 code of country
#' @param level 1 or 2
#' @param simple 1 to 3 - parameter for ArcGIS API call
#' @param simplify Logical: whether to simplify or not
#' @param dTolerance parameter passed to [sf::st_simplify()]
#' 
#' @importFrom httr GET
#' @importFrom sf st_read st_simplify
#' @import countrycode 
#' @import here
#' @import ggplot2
#'
#' @return sf object
#' @export
f_get_admin2_boundaries <- function(ISO3,
                                    level,
                                    simple ,
                                    simplify = TRUE, 
                                    dTolerance = 500){

  stopifnot(ISO3 %in% countrycode::codelist$iso3c)
  # generate query string
  # from: https://gis.unhcr.org/arcgis/rest/services/core_v2/wrl_polbnd_adm2_a_unhcr/MapServer/0/query
  
   api_query <- paste0(
  "https://gis.unhcr.org/arcgis/rest/services/core_v2/wrl_polbnd_adm",
  level,
  "_a_unhcr/MapServer/0/",
  "query?where=ISO3+%3D+%27",
     ISO3,
  "%27&text=&",
  "objectIds=&",
  "time=&",
  "geometry=&",
  "geometryType=esriGeometryEnvelope&",
  "inSR=&",
  "spatialRel=esriSpatialRelIntersects&",
  "distance=&",
  "units=esriSRUnit_Foot&",
  "relationParam=&",
  "outFields=*&",
 # "&outFields=pcode%2C+adm2_source_code%2C+gis_name%2C&",
  "returnGeometry=true&returnTrueCurves=false&",
  "maxAllowableOffset=&",
  "geometryPrecision=",  simple, "&",
  "outSR=&havingClause=&",
  "returnIdsOnly=false&",
  "returnCountOnly=false&",
  "orderByFields=&",
  "groupByFieldsForStatistics=&",
  "outStatistics=&",
  "returnZ=false&",
  "returnM=false&",
  "gdbVersion=&",
  "historicMoment=&",
  "returnDistinctValues=false&",
  "resultOffset=&",
  "resultRecordCount=&",
  "returnExtentOnly=false&",
  "datumTransformation=&",
  "parameterValues=&",
  "rangeValues=&",
  "quantizationParameters=&",
  "featureEncoding=esriDefault&",
  "f=geojson")


  # read and create feature table
   message("Trying to get data for ", 
           countrycode::countrycode(ISO3,
                                    "iso3c",
                                    "country.name"),
           ".")
   
   
    tryCatch(
        #try to do this
        {
        #some expression
        startTime <- Sys.time()
        resp <- httr::GET(api_query)  # , timeout(600)
        endTime <- Sys.time()
        logtxt <-endTime - starTime
        message("Got API response for ",
                ISO3, " in ",
                log.txt , " .....\n")
        },
        #if an error occurs, tell me the error
          error=function(e) {
             # message("Failed when pulling for ",
             #         ISO3, "  " , " ........\n")
              res <- e
        }
     )
   
   
  
  ## in case we got something then start QA -
  if ( exists("resp") ) {

      if (httr::http_error(resp)) {
          stop(
            sprintf(
              "ArcGIS request failed [%s]\n%s\n<%s>", 
              status_code(resp),
              parsed$message,
              parsed$documentation_url
             ),
            call. = FALSE
          )
            res <- sprintf(
              "ArcGIS request failed [%s]\n%s\n<%s>", 
              status_code(resp),
              parsed$message,
              parsed$documentation_url
             )
        } else if ( httr::http_type(resp) != "application/geo+json") {
         res <- "API did not return geojson" #, call. = FALSE) 
        } else { cat("  ")}
       
      ### Now checking that the geojson can be read... 
      rm(df_geom) 
      tryCatch(
            #try to do this
            {
            #some expression
            df_geom <- sf::st_read(resp, quiet = TRUE)
            message("Geometry size for ", ISO3, " is ", object.size(df_geom) ,  "......")
            },
            #if an error occurs, tell me the error
              error=function(e) {
                  message('An Error Occurred')
                  res <- e
            }
         )
      
      ## in case we got something then start QA -
      if ( exists("df_geom") ) {
      
        if(any(is.na(df_geom$gis_name))){
          warning("NAs found in gis_name for: ", ISO3, "\n")
        }
        
        if(any(duplicated(df_geom$gis_name)) ){
          cat( paste0( sum(duplicated(df_geom$gis_name) ),
                       " duplicate in gis_name for: ", ISO3, "\n") )
           }
      
        # if(any(is.na(df_geom$adm2_source_code))){
        #   warning("NAs found in adm2_source_code for: ", ISO3, "\n")
        # }
        # 
        # if(any(duplicated(df_geom$adm2_source_code)) ){
        #   cat( paste0( sum(duplicated(df_geom$adm2_source_code) ),
        #                " duplicate in adm2_source_code for: ", ISO3, "\n") )
        #     }
        # 
        
        
        if(any(is.na(df_geom$pcode))){
          warning("NAs found in pcode for: ", ISO3, "\n")
        }
        
        if(any(duplicated(df_geom$pcode)) ){
          cat( paste0( sum(duplicated(df_geom$pcode) ),
                       " duplicate in pcode for: ", ISO3, "\n") )
        }
         
        
        ## Check if the pcode include isocode 2 letters, or iso code 2 letters
         
         
      ### Checking if simplification works
      if(simplify){
        ## Check that simplification work
          tryCatch(
            #try to do this
            {
            #some expression
            df_geom2 <- sf::st_simplify(df_geom, 
                                   preserveTopology = TRUE, 
                                   dTolerance = dTolerance) 
               message("Simplified Geometry size for ", ISO3, " is ", object.size(df_geom2) ,  " aka ",
                       round(
                         as.numeric(object.size(df_geom2)) /
                        as.numeric(object.size(df_geom)) 
                        *100,2), 
                       "% .....\n")
            },
            #if an error occurs, tell me the error
            error=function(e) {
                message('An Error Occurred during geometry simplification')
                print(e)
            },
            #if a warning occurs, tell me the warning
            warning=function(w) {
                message('A Warning Occurred during geometry simplification')
                print(w)
                res <- NA
            }
         )
          
      } else { cat("No simplification was requested ")   }
        
      if ( exists("df_geom2") ) {
            res <- df_geom2
          } else { 
          res <- df_geom
          }
       ## Save
       saveRDS(res, file = here::here("inst/geom", paste0(ISO3,"_level_", level,".RDS") ))
       ## plot
       print( ggplot2::ggplot(data = res ) + 
          ggplot2::geom_sf() + 
          ggplot2::theme_void() +
          ggplot2::labs(
            title = paste0(
              countrycode::countrycode(ISO3, "iso3c", "country.name"),
              ": ",
              nrow(df_geom),
              " admin units level ", level
            ),
            subtitle = paste0("Average Single Polygon Disk Size: ",
                             round(object.size(res)/nrow(df_geom),0)),
            caption = paste0("Source: ",unique(res$source))
          )
       )
      }  
  }
  
  return(res)
}

```
  
```{r example-f_get_admin2_boundaries}
## The test is actually the QA process! 
library(countrycode)
ctr <- countrycode::codelist |>
       dplyr::filter( ! is.na(iso3c) )  |>
       dplyr::filter(unhcr.region == "The Americas" ) |>
       dplyr::select(country.name.en, iso3c) |>
       dplyr::arrange( iso3c)
ctr
ctr <- ctr |>
       dplyr::select(iso3c)  |>
       dplyr::pull()  
## test on faulty.. with ArcGIS server simpification.. 
BRA2 <- f_get_admin2_boundaries( ISO3 = "BRA",
                                level = 2,
                                 simple = 1, 
                                simplify = TRUE,
                                dTolerance = 500)

# ECU <- f_get_admin2_boundaries(ISO3 = "ECU",level = 2, simplify = TRUE, dTolerance = 500)
# GTM <- f_get_admin2_boundaries(ISO3 = "GTM",level = 2, simplify = TRUE, dTolerance = 500)
# GTM1 <- f_get_admin2_boundaries(ISO3 = "GTM",level = 1, simple = NULL, simplify = TRUE, dTolerance = 500)
# CRI <- f_get_admin2_boundaries(ISO3 = "CRI",level = 2, simplify = TRUE, dTolerance = 500)
# CHL <- f_get_admin2_boundaries(ISO3 = "CHL",level = 2, simplify = TRUE, dTolerance = 500)
# COL <- f_get_admin2_boundaries(ISO3 = "COL",level = 2, simplify = TRUE, dTolerance = 500)
# MEX <- f_get_admin2_boundaries(ISO3 = "MEX",level = 2, simplify = TRUE, dTolerance = 500)


for ( code  in ctr ) { 
  # code <- "GTM"
  #cat (paste0(code,"\n"))
  t2 <- f_get_admin2_boundaries(ISO3 = code,
                               level = 2,
                               simple = NULL,
                               simplify = TRUE, 
                               dTolerance = 500) 
  t1 <- f_get_admin2_boundaries(ISO3 = code,
                               level = 1,
                               simple = NULL,
                               simplify = TRUE, 
                               dTolerance = 500) 
  ## Merge back aadm1_name in t2
  if ( any( class(t2) !="character" &
            nrow(t2) > 0 &
            class(t1) !="character" &
            nrow(t1) > 0  ) ) {
      t2 |>
      dplyr::mutate(adm1_pcode = as.character(adm1_pcode)) |>
      dplyr::left_join( t1 |>
                        sf::st_drop_geometry() |>
                        dplyr::select(pcode, gis_name) |>
                        dplyr::distinct() |>
                        dplyr::rename(adm1_pcode = pcode,
                                      adm1_name = gis_name ) |>
                        dplyr::mutate(adm1_pcode = as.character(adm1_pcode)) ,
          by = c("adm1_pcode")) |>
          dplyr::select(iso3, pcode, gis_name, adm2_source_code, 
                        adm1_pcode,adm1_name,
                        gis_status,source, src_date,  geometry ) |>
          dplyr::filter(gis_status == 14 ) |>
          saveRDS(  file = here::here("inst/geom", paste0(code,".RDS") ))
     }
  }
```
  
```{r tests-f_get_admin2_boundaries}
test_that("f_get_admin2_boundaries works", {
  expect_true(inherits(f_get_admin2_boundaries, "function")) 
})
```


# f_get_admin2_cod
    
```{r function-f_get_admin2_cod}
#' Get admin2 polygons from API
#'
#' Queries the COD API sever to return admin2 geometry and pcode for a specific
#' country based on iso name.
#' As the resulting data is expected to be used in a shinyApp, the geomtry is simplified
#'
#' @param ISO3 ISO3 code of country
#' @param simplify Logical: whether to simplify or not
#' @param dTolerance parameter passed to [sf::st_simplify()]
#' @importFrom httr GET
#' @importFrom sf st_read st_simplify
#' @import countrycode 
#' @import here
#' @import ggplot2 
#' @return sf object
#' @export

f_get_admin2_cod <- function(ISO3, simplify = TRUE, dTolerance = 500){

  stopifnot(ISO3 %in% countrycode::codelist$iso3c)
# server <- "https://beta.itos.uga.edu/CODV2API/api/v1/cod-ab/locations/"
# parameter <- "/versions/current/geojson/2"

  
  # generate query string
# https://apps.itos.uga.edu/codv2api/api/v1/themes/cod-ab/locations/BFA/versions/current/geoJSON/1
server <- "https://apps.itos.uga.edu/codv2api/api/v1/themes/cod-ab/locations/"
parameter <- "/versions/current/geoJSON/2"



api_query <- paste0( server, ISO3, parameter)
#read and create feature table

df_geom <- sf::st_read(api_query)

if(any(is.na(df_geom$adm2_source_code))){
warning("NAs found in Admin2 codes...")
}

if(simplify){
sf::st_simplify(df_geom, preserveTopology = TRUE, dTolerance = dTolerance)
} else {
df_geom
}
 ## Save
 saveRDS(df_geom, file = here::here("inst/geom", paste0(ISO3,"_cod.RDS") ))
 ## plot
 print( ggplot2::ggplot(data = df_geom ) + 
          ggplot2::geom_sf() + 
          ggplot2::theme_void() +
          ggplot2::labs(
            title = paste0(
              countrycode::countrycode(ISO3, "iso3c", "country.name"),
              ": ",
              nrow(df_geom),
              " admin unit level2."
            ),
            subtitle = paste0("Average Single Polygon Disk Size: ",
                             round(object.size(df_geom)/nrow(df_geom),0))
          ))
 return(df_geom)
 
 }

 
```
  
```{r example-f_get_admin2_cod}
#GTM <- f_get_admin2_cod("GTM", simplify = TRUE, dTolerance = 500)
```
  
```{r tests-f_get_admin2_cod}
test_that("f_get_admin2_cod works", {
  expect_true(inherits(f_get_admin2_cod, "function")) 
})
```
  



```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_full.Rmd", vignette_name = "Get started")
```


