# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Get admin2 polygons from API
#'
#' Queries the COD API sever to return admin2 geometry and pcode for a specific
#' country based on iso name.
#' As the resulting data is expected to be used in a shinyApp, the geomtry is simplified
#'
#' @param ISO3 ISO3 code of country
#' @param simplify Logical: whether to simplify or not
#' @param dTolerance parameter passed to [sf::st_simplify()]
#' @importFrom httr GET
#' @importFrom sf st_read st_simplify
#' @import countrycode 
#' @import here
#' @import ggplot2 
#' @return sf object
#' @export

#' @examples
#' #GTM <- f_get_admin2_cod("GTM", simplify = TRUE, dTolerance = 500)
f_get_admin2_cod <- function(ISO3, simplify = TRUE, dTolerance = 500){

  stopifnot(ISO3 %in% countrycode::codelist$iso3c)
# server <- "https://beta.itos.uga.edu/CODV2API/api/v1/cod-ab/locations/"
# parameter <- "/versions/current/geojson/2"

  
  # generate query string
# https://apps.itos.uga.edu/codv2api/api/v1/themes/cod-ab/locations/BFA/versions/current/geoJSON/1
server <- "https://apps.itos.uga.edu/codv2api/api/v1/themes/cod-ab/locations/"
parameter <- "/versions/current/geoJSON/2"



api_query <- paste0( server, ISO3, parameter)
#read and create feature table

df_geom <- sf::st_read(api_query)

if(any(is.na(df_geom$adm2_source_code))){
warning("NAs found in Admin2 codes...")
}

if(simplify){
sf::st_simplify(df_geom, preserveTopology = TRUE, dTolerance = dTolerance)
} else {
df_geom
}
 ## Save
 saveRDS(df_geom, file = here::here("inst/geom", paste0(ISO3,"_cod.RDS") ))
 ## plot
 print( ggplot2::ggplot(data = df_geom ) + 
          ggplot2::geom_sf() + 
          ggplot2::theme_void() +
          ggplot2::labs(
            title = paste0(
              countrycode::countrycode(ISO3, "iso3c", "country.name"),
              ": ",
              nrow(df_geom),
              " admin unit level2."
            ),
            subtitle = paste0("Average Single Polygon Disk Size: ",
                             round(object.size(df_geom)/nrow(df_geom),0))
          ))
 return(df_geom)
 
 }

 
