# WARNING - Generated by {fusen} from /dev/flat_full.Rmd: do not edit by hand

#' Get admin2 polygons from API
#'
#' Queries the gis.unhcr.org sever to return admin2 shape files for a specific
#' country. Some of the files returned are heavy, and the server also seems to
#' fail or time out every now and then. Also, some admin2 codes are not in the
#' expected format.
#'
#' @param ISO3 ISO3 code of country
#' @param simplify Logical: whether to simplify or not
#' @param dTolerance parameter passed to [sf::st_simplify()]
#' 
#' @importFrom sf st_read st_simplify
#' @import countrycode 
#'
#' @return sf object
#' @export
#' @examples
#' ## The test is actually the QA process! 
#' library(countrycode)
#' ctr <- countrycode::codelist |>
#'        dplyr::filter( ! is.na(iso3c) )  |>
#'        dplyr::filter(continent == "Americas" ) |>
#'        dplyr::select(country.name.en, iso3c)
#' ctr
#' ctr <- ctr |>
#'        dplyr::select(iso3c)  |>
#'        dplyr::pull()  
#' 
#' 
#' # 
#' # BRA <- f_get_admin2_boundaries(ISO3 = "BRA", simplify = TRUE, dTolerance = 500)
#' # ECU <- f_get_admin2_boundaries(ISO3 = "ECU", simplify = TRUE, dTolerance = 500)
#' # GTM <- f_get_admin2_boundaries(ISO3 = "GTM", simplify = TRUE, dTolerance = 500)
#' # CRI <- f_get_admin2_boundaries(ISO3 = "CRI", simplify = TRUE, dTolerance = 500)
#' # CHL <- f_get_admin2_boundaries(ISO3 = "CHL", simplify = TRUE, dTolerance = 500)
#' # COL <- f_get_admin2_boundaries(ISO3 = "COL", simplify = TRUE, dTolerance = 500)
#' # MEX <- f_get_admin2_boundaries(ISO3 = "MEX", simplify = TRUE, dTolerance = 500)
#' 
#' 
#' for ( code  in ctr )
#'  { t <- f_get_admin2_boundaries(ISO3 = code, simplify = TRUE, dTolerance = 500) }
f_get_admin2_boundaries <- function(ISO3, simplify = TRUE, dTolerance = 500){

  stopifnot(ISO3 %in% countrycode::codelist$iso3c)

  # generate query string
  # from: https://gis.unhcr.org/arcgis/rest/services/core_v2/wrl_polbnd_adm2_a_unhcr/MapServer/0/query
  api_query <- paste0(
    "https://gis.unhcr.org/arcgis/rest/services/core_v2/wrl_polbnd_adm2_a_unhcr/",
    "MapServer/0/query?where=ISO3+%3D+%27", ISO3,
    "%27&text=&objectIds=&time=&geometry=",
    "&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects",
    "&distance=&units=esriSRUnit_Foot&relationParam=",
    "&outFields=pcode%2C+adm2_source_code%2C+gis_name&returnGeometry=true&",
    "returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&",
    "havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&",
    "groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&",
    "gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=",
    "&resultRecordCount=&returnExtentOnly=false&datumTransformation=&",
    "parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson")

  # read and create feature table
  df_geom <- sf::st_read(api_query)
  
  message("Fetching geometry for ", ISO3, "........")
  
  ## QA Start 
  
  ## Checking if there is a name
  if(any(is.na(df_geom$adm2_source_code))){
    warning("NAs found in Admin2 codes for: ", ISO3)
  }
  
  
  ### Checking if simplification works
  if(simplify){
    sf::st_simplify(df_geom, preserveTopology = TRUE, dTolerance = dTolerance)
  } else {
    df_geom
  }



}

